export const withCentralBank = [
  {
    currency: "Afghan Afghani",
    code: "AFN",
    symbol: "؋",
    country: "Afghanistan",
    country_code: "AF",
  },
  {
    currency: "Albanian Lek",
    code: "ALL",
    symbol: "L",
    country: "Albania",
    country_code: "AL",
  },
  {
    currency: "Algerian Dinar",
    code: "DZD",
    symbol: "د.ج",
    country: "Algeria",
    country_code: "DZ",
  },
  {
    currency: "Angolan Kwanza",
    code: "AOA",
    symbol: "Kz",
    country: "Angola",
    country_code: "AO",
  },
  {
    currency: "Argentine Peso",
    code: "ARS",
    symbol: "$",
    country: "Argentina",
    country_code: "AR",
  },
  {
    currency: "Armenian Dram",
    code: "AMD",
    symbol: "֏",
    country: "Armenia",
    country_code: "AM",
  },
  {
    currency: "Australian Dollar",
    code: "AUD",
    symbol: "$",
    country: "Australia",
    country_code: "AU",
    central_bank: "Reserve Bank of Australia",
  },
  {
    currency: "Azerbaijani Manat",
    code: "AZN",
    symbol: "₼",
    country: "Azerbaijan",
    country_code: "AZ",
  },
  {
    currency: "Bahamian Dollar",
    code: "BSD",
    symbol: "$",
    country: "Bahamas",
    country_code: "BS",
  },
  {
    currency: "Bahraini Dinar",
    code: "BHD",
    symbol: ".د.ب",
    country: "Bahrain",
    country_code: "BH",
  },
  {
    currency: "Bangladeshi Taka",
    code: "BDT",
    symbol: "৳",
    country: "Bangladesh",
    country_code: "BD",
  },
  {
    currency: "Barbadian Dollar",
    code: "BBD",
    symbol: "$",
    country: "Barbados",
    country_code: "BB",
  },
  {
    currency: "Belarusian Ruble",
    code: "BYN",
    symbol: "Br",
    country: "Belarus",
    country_code: "BY",
  },
  {
    currency: "Belgian Euro",
    code: "EUR",
    symbol: "€",
    country: "Belgium",
    country_code: "BE",
    central_bank: "European Central Bank",
  },
  {
    currency: "Belize Dollar",
    code: "BZD",
    symbol: "$",
    country: "Belize",
    country_code: "BZ",
  },
  {
    currency: "Bermudian Dollar",
    code: "BMD",
    symbol: "$",
    country: "Bermuda",
    country_code: "BM",
  },
  {
    currency: "Bhutanese Ngultrum",
    code: "BTN",
    symbol: "Nu.",
    country: "Bhutan",
    country_code: "BT",
  },
  {
    currency: "Bolivian Boliviano",
    code: "BOB",
    symbol: "Bs.",
    country: "Bolivia",
    country_code: "BO",
  },
  {
    currency: "Bosnia and Herzegovina Convertible Mark",
    code: "BAM",
    symbol: "KM",
    country: "Bosnia and Herzegovina",
    country_code: "BA",
  },
  {
    currency: "Botswana Pula",
    code: "BWP",
    symbol: "P",
    country: "Botswana",
    country_code: "BW",
  },
  {
    currency: "Brazilian Real",
    code: "BRL",
    symbol: "R$",
    country: "Brazil",
    country_code: "BR",
    central_bank: "Central Bank of Brazil",
  },
  {
    currency: "British Pound",
    code: "GBP",
    symbol: "£",
    country: "United Kingdom",
    country_code: "GB",
    central_bank: "Bank of England",
  },
  {
    currency: "Brunei Dollar",
    code: "BND",
    symbol: "$",
    country: "Brunei",
    country_code: "BN",
  },
  {
    currency: "Bulgarian Lev",
    code: "BGN",
    symbol: "лв",
    country: "Bulgaria",
    country_code: "BG",
  },
  {
    currency: "Burundian Franc",
    code: "BIF",
    symbol: "FBu",
    country: "Burundi",
    country_code: "BI",
  },
];
